// Code generated by MockGen. DO NOT EDIT.
// Source: executor_config_repository.go
//
// Generated by this command:
//
//	mockgen -source=executor_config_repository.go -destination=executor_config_repository_mock_test.go -package=command
//

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"

	model "github.com/LerianStudio/flowker/pkg/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutorConfigRepository is a mock of ExecutorConfigRepository interface.
type MockExecutorConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockExecutorConfigRepositoryMockRecorder is the mock recorder for MockExecutorConfigRepository.
type MockExecutorConfigRepositoryMockRecorder struct {
	mock *MockExecutorConfigRepository
}

// NewMockExecutorConfigRepository creates a new mock instance.
func NewMockExecutorConfigRepository(ctrl *gomock.Controller) *MockExecutorConfigRepository {
	mock := &MockExecutorConfigRepository{ctrl: ctrl}
	mock.recorder = &MockExecutorConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutorConfigRepository) EXPECT() *MockExecutorConfigRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExecutorConfigRepository) Create(ctx context.Context, executorConfig *model.ExecutorConfiguration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, executorConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockExecutorConfigRepositoryMockRecorder) Create(ctx, executorConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExecutorConfigRepository)(nil).Create), ctx, executorConfig)
}

// Delete mocks base method.
func (m *MockExecutorConfigRepository) Delete(ctx context.Context, id uuid.UUID, expectedStatus model.ExecutorConfigurationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, expectedStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExecutorConfigRepositoryMockRecorder) Delete(ctx, id, expectedStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExecutorConfigRepository)(nil).Delete), ctx, id, expectedStatus)
}

// ExistsByName mocks base method.
func (m *MockExecutorConfigRepository) ExistsByName(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByName", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByName indicates an expected call of ExistsByName.
func (mr *MockExecutorConfigRepositoryMockRecorder) ExistsByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByName", reflect.TypeOf((*MockExecutorConfigRepository)(nil).ExistsByName), ctx, name)
}

// FindByID mocks base method.
func (m *MockExecutorConfigRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.ExecutorConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.ExecutorConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockExecutorConfigRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockExecutorConfigRepository)(nil).FindByID), ctx, id)
}

// FindByName mocks base method.
func (m *MockExecutorConfigRepository) FindByName(ctx context.Context, name string) (*model.ExecutorConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*model.ExecutorConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockExecutorConfigRepositoryMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockExecutorConfigRepository)(nil).FindByName), ctx, name)
}

// List mocks base method.
func (m *MockExecutorConfigRepository) List(ctx context.Context, filter ExecutorConfigListFilter) (*ExecutorConfigListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].(*ExecutorConfigListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockExecutorConfigRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockExecutorConfigRepository)(nil).List), ctx, filter)
}

// Update mocks base method.
func (m *MockExecutorConfigRepository) Update(ctx context.Context, executorConfig *model.ExecutorConfiguration, expectedStatus model.ExecutorConfigurationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, executorConfig, expectedStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockExecutorConfigRepositoryMockRecorder) Update(ctx, executorConfig, expectedStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExecutorConfigRepository)(nil).Update), ctx, executorConfig, expectedStatus)
}
