// Code generated by MockGen. DO NOT EDIT.
// Source: provider_config_repository.go
//
// Generated by this command:
//
//	mockgen -source=provider_config_repository.go -destination=provider_config_repository_mock_test.go -package=command
//

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"

	model "github.com/LerianStudio/flowker/pkg/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockProviderConfigRepository is a mock of ProviderConfigRepository interface.
type MockProviderConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProviderConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockProviderConfigRepositoryMockRecorder is the mock recorder for MockProviderConfigRepository.
type MockProviderConfigRepositoryMockRecorder struct {
	mock *MockProviderConfigRepository
}

// NewMockProviderConfigRepository creates a new mock instance.
func NewMockProviderConfigRepository(ctrl *gomock.Controller) *MockProviderConfigRepository {
	mock := &MockProviderConfigRepository{ctrl: ctrl}
	mock.recorder = &MockProviderConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderConfigRepository) EXPECT() *MockProviderConfigRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProviderConfigRepository) Create(ctx context.Context, providerConfig *model.ProviderConfiguration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, providerConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProviderConfigRepositoryMockRecorder) Create(ctx, providerConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProviderConfigRepository)(nil).Create), ctx, providerConfig)
}

// Delete mocks base method.
func (m *MockProviderConfigRepository) Delete(ctx context.Context, id uuid.UUID, expectedStatus model.ProviderConfigurationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, expectedStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProviderConfigRepositoryMockRecorder) Delete(ctx, id, expectedStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProviderConfigRepository)(nil).Delete), ctx, id, expectedStatus)
}

// ExistsByName mocks base method.
func (m *MockProviderConfigRepository) ExistsByName(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByName", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByName indicates an expected call of ExistsByName.
func (mr *MockProviderConfigRepositoryMockRecorder) ExistsByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByName", reflect.TypeOf((*MockProviderConfigRepository)(nil).ExistsByName), ctx, name)
}

// FindByID mocks base method.
func (m *MockProviderConfigRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.ProviderConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.ProviderConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockProviderConfigRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockProviderConfigRepository)(nil).FindByID), ctx, id)
}

// FindByName mocks base method.
func (m *MockProviderConfigRepository) FindByName(ctx context.Context, name string) (*model.ProviderConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*model.ProviderConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockProviderConfigRepositoryMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockProviderConfigRepository)(nil).FindByName), ctx, name)
}

// List mocks base method.
func (m *MockProviderConfigRepository) List(ctx context.Context, filter ProviderConfigListFilter) (*ProviderConfigListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].(*ProviderConfigListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProviderConfigRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProviderConfigRepository)(nil).List), ctx, filter)
}

// Update mocks base method.
func (m *MockProviderConfigRepository) Update(ctx context.Context, providerConfig *model.ProviderConfiguration, expectedStatus model.ProviderConfigurationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, providerConfig, expectedStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProviderConfigRepositoryMockRecorder) Update(ctx, providerConfig, expectedStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProviderConfigRepository)(nil).Update), ctx, providerConfig, expectedStatus)
}
