// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/command/workflow_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/command/workflow_repository.go -destination=internal/services/command/workflow_repository_mock_test.go -package=command
//

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"

	model "github.com/LerianStudio/flowker/pkg/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkflowRepository is a mock of WorkflowRepository interface.
type MockWorkflowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkflowRepositoryMockRecorder is the mock recorder for MockWorkflowRepository.
type MockWorkflowRepositoryMockRecorder struct {
	mock *MockWorkflowRepository
}

// NewMockWorkflowRepository creates a new mock instance.
func NewMockWorkflowRepository(ctrl *gomock.Controller) *MockWorkflowRepository {
	mock := &MockWorkflowRepository{ctrl: ctrl}
	mock.recorder = &MockWorkflowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowRepository) EXPECT() *MockWorkflowRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWorkflowRepository) Create(ctx context.Context, workflow *model.Workflow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, workflow)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWorkflowRepositoryMockRecorder) Create(ctx, workflow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkflowRepository)(nil).Create), ctx, workflow)
}

// Delete mocks base method.
func (m *MockWorkflowRepository) Delete(ctx context.Context, id uuid.UUID, expectedStatus model.WorkflowStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, expectedStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkflowRepositoryMockRecorder) Delete(ctx, id, expectedStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkflowRepository)(nil).Delete), ctx, id, expectedStatus)
}

// ExistsByName mocks base method.
func (m *MockWorkflowRepository) ExistsByName(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByName", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByName indicates an expected call of ExistsByName.
func (mr *MockWorkflowRepositoryMockRecorder) ExistsByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByName", reflect.TypeOf((*MockWorkflowRepository)(nil).ExistsByName), ctx, name)
}

// FindByID mocks base method.
func (m *MockWorkflowRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockWorkflowRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockWorkflowRepository)(nil).FindByID), ctx, id)
}

// FindByName mocks base method.
func (m *MockWorkflowRepository) FindByName(ctx context.Context, name string) (*model.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*model.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockWorkflowRepositoryMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockWorkflowRepository)(nil).FindByName), ctx, name)
}

// List mocks base method.
func (m *MockWorkflowRepository) List(ctx context.Context, filter WorkflowListFilter) (*WorkflowListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].(*WorkflowListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockWorkflowRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWorkflowRepository)(nil).List), ctx, filter)
}

// Update mocks base method.
func (m *MockWorkflowRepository) Update(ctx context.Context, workflow *model.Workflow, expectedStatus model.WorkflowStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, workflow, expectedStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWorkflowRepositoryMockRecorder) Update(ctx, workflow, expectedStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWorkflowRepository)(nil).Update), ctx, workflow, expectedStatus)
}
