// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapters/http/in/workflow/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/adapters/http/in/workflow/handler.go -destination=internal/adapters/http/in/workflow/mock_test.go -package=workflow_test
//

// Package workflow_test is a generated GoMock package.
package workflow_test

import (
	context "context"
	reflect "reflect"

	query "github.com/LerianStudio/flowker/internal/services/query"
	model "github.com/LerianStudio/flowker/pkg/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandService is a mock of CommandService interface.
type MockCommandService struct {
	ctrl     *gomock.Controller
	recorder *MockCommandServiceMockRecorder
	isgomock struct{}
}

// MockCommandServiceMockRecorder is the mock recorder for MockCommandService.
type MockCommandServiceMockRecorder struct {
	mock *MockCommandService
}

// NewMockCommandService creates a new mock instance.
func NewMockCommandService(ctrl *gomock.Controller) *MockCommandService {
	mock := &MockCommandService{ctrl: ctrl}
	mock.recorder = &MockCommandServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandService) EXPECT() *MockCommandServiceMockRecorder {
	return m.recorder
}

// Activate mocks base method.
func (m *MockCommandService) Activate(ctx context.Context, id uuid.UUID) (*model.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", ctx, id)
	ret0, _ := ret[0].(*model.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Activate indicates an expected call of Activate.
func (mr *MockCommandServiceMockRecorder) Activate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockCommandService)(nil).Activate), ctx, id)
}

// Clone mocks base method.
func (m *MockCommandService) Clone(ctx context.Context, id uuid.UUID, input *model.CloneWorkflowInput) (*model.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone", ctx, id, input)
	ret0, _ := ret[0].(*model.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clone indicates an expected call of Clone.
func (mr *MockCommandServiceMockRecorder) Clone(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockCommandService)(nil).Clone), ctx, id, input)
}

// CreateFromTemplate mocks base method.
func (m *MockCommandService) CreateFromTemplate(ctx context.Context, input *model.CreateWorkflowFromTemplateInput) (*model.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFromTemplate", ctx, input)
	ret0, _ := ret[0].(*model.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFromTemplate indicates an expected call of CreateFromTemplate.
func (mr *MockCommandServiceMockRecorder) CreateFromTemplate(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFromTemplate", reflect.TypeOf((*MockCommandService)(nil).CreateFromTemplate), ctx, input)
}

// Create mocks base method.
func (m *MockCommandService) Create(ctx context.Context, input *model.CreateWorkflowInput) (*model.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*model.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCommandServiceMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommandService)(nil).Create), ctx, input)
}

// Deactivate mocks base method.
func (m *MockCommandService) Deactivate(ctx context.Context, id uuid.UUID) (*model.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deactivate", ctx, id)
	ret0, _ := ret[0].(*model.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deactivate indicates an expected call of Deactivate.
func (mr *MockCommandServiceMockRecorder) Deactivate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deactivate", reflect.TypeOf((*MockCommandService)(nil).Deactivate), ctx, id)
}

// MoveToDraft mocks base method.
func (m *MockCommandService) MoveToDraft(ctx context.Context, id uuid.UUID) (*model.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveToDraft", ctx, id)
	ret0, _ := ret[0].(*model.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveToDraft indicates an expected call of MoveToDraft.
func (mr *MockCommandServiceMockRecorder) MoveToDraft(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToDraft", reflect.TypeOf((*MockCommandService)(nil).MoveToDraft), ctx, id)
}

// Delete mocks base method.
func (m *MockCommandService) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommandServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommandService)(nil).Delete), ctx, id)
}

// Update mocks base method.
func (m *MockCommandService) Update(ctx context.Context, id uuid.UUID, input *model.UpdateWorkflowInput) (*model.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, input)
	ret0, _ := ret[0].(*model.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCommandServiceMockRecorder) Update(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCommandService)(nil).Update), ctx, id, input)
}

// MockQueryService is a mock of QueryService interface.
type MockQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockQueryServiceMockRecorder
	isgomock struct{}
}

// MockQueryServiceMockRecorder is the mock recorder for MockQueryService.
type MockQueryServiceMockRecorder struct {
	mock *MockQueryService
}

// NewMockQueryService creates a new mock instance.
func NewMockQueryService(ctrl *gomock.Controller) *MockQueryService {
	mock := &MockQueryService{ctrl: ctrl}
	mock.recorder = &MockQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryService) EXPECT() *MockQueryServiceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockQueryService) GetByID(ctx context.Context, id uuid.UUID) (*model.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockQueryServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockQueryService)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockQueryService) GetByName(ctx context.Context, name string) (*model.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*model.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockQueryServiceMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockQueryService)(nil).GetByName), ctx, name)
}

// List mocks base method.
func (m *MockQueryService) List(ctx context.Context, filter query.WorkflowListFilter) (*query.WorkflowListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].(*query.WorkflowListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockQueryServiceMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockQueryService)(nil).List), ctx, filter)
}
