// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapters/http/in/health/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/adapters/http/in/health/handler.go -destination=internal/adapters/http/in/health/mock_test.go -package=health_test
//

// Package health_test is a generated GoMock package.
package health_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabaseChecker is a mock of DatabaseChecker interface.
type MockDatabaseChecker struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseCheckerMockRecorder
	isgomock struct{}
}

// MockDatabaseCheckerMockRecorder is the mock recorder for MockDatabaseChecker.
type MockDatabaseCheckerMockRecorder struct {
	mock *MockDatabaseChecker
}

// NewMockDatabaseChecker creates a new mock instance.
func NewMockDatabaseChecker(ctrl *gomock.Controller) *MockDatabaseChecker {
	mock := &MockDatabaseChecker{ctrl: ctrl}
	mock.recorder = &MockDatabaseCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseChecker) EXPECT() *MockDatabaseCheckerMockRecorder {
	return m.recorder
}

// IsConnected mocks base method.
func (m *MockDatabaseChecker) IsConnected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConnected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConnected indicates an expected call of IsConnected.
func (mr *MockDatabaseCheckerMockRecorder) IsConnected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConnected", reflect.TypeOf((*MockDatabaseChecker)(nil).IsConnected))
}

// Ping mocks base method.
func (m *MockDatabaseChecker) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDatabaseCheckerMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDatabaseChecker)(nil).Ping), ctx)
}
